### ISSUE TITLE
Customer not changing Group ID

### ISSUE THREAD

**Issue by gcampedelli** [meanbee/magento2-vip-membership#1]
Hello, 
I found two problems. 
1- Customer is not changing from group
2- Cron job is getting an attribute Invalid attribute name: vip_expiry_date. I've removed _date from the variable and I got success. 
Am I missing anything. The above solution is right? How can I get customer to change from group??

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
